name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub container registry
        run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
      - name: Build docker image
        run: docker build --tag $DOCKER_IMAGE .
      - name: Push to container registry
        run: docker push $DOCKER_IMAGE
  run-app:
    needs: deploy-app
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/${{ github.repository }}:latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.FREEBOX_URL }}
          username: ${{ secrets.FREEBOX_USER }}
          key: ${{ secrets.FREEBOX_SSH_KEY }}
          envs: DOCKER_IMAGE
          script_stop: true
          script: |
            name="divergent-api"
            url="${name}.kibalabs.com"
            dockerImage="${DOCKER_IMAGE}"
            version="TBD"
            varsFile=~/.${name}.vars
            docker pull ${dockerImage}
            docker stop ${name} && docker rm ${name} || true
            docker run \
                --name ${name} \
                --detach \
                --publish-all \
                --restart on-failure \
                --env NAME=$name \
                --env VERSION=$version \
                --env VIRTUAL_HOST=$url \
                --env LETSENCRYPT_HOST=$url \
                --env-file ${varsFile} \
                ${dockerImage}
